### ISSUE TITLE
[Test] Mockito verwenden für testimplementationen in MapTest

### ISSUE THREAD

**Issue by MaxRBecker** [under-the-oaks/ColdCase-Client#76]
See: https://github.com/under-the-oaks/ColdCase-Client/pull/72#discussion_r1842729457 

libGDX also has a Headless Application Class, see: https://stackoverflow.com/questions/25612660/creating-texture-in-headless-libgdx-unit-tests 

maybe we can use that

**Comment by jonachri** [comment]
Or not
